export const filterSlang = (inputText) => {
      const slangDictionary = {
        "how dare you": "how 😠💢😈 you",
          "make you pay": 'make you 📉💸',
          "keep quiet": 'keep🔕quiet',
          "ruin": 'ru💀☠️👽💀',
          "destroy": 'des🤯💣🗡️🏴‍☠️',
          "burn": 'bu🔥♨️🔥', 
          "hit": '🔫🏹💥',
          "strike": 'str🎯🥊💥ike',
          "assault": '(❦◡❦)︻デ═一',
          "attack": '👊👊',
          'kill': 'Pew! Pew! 🔫',
          'killed': 'Pew! Pew! 🔫',
          'die': '⚰😴💤',
          'dead': '⚰😴💤',
          'end you': '🔚⚰👻',
          'eliminate': 'elimi❌🚷☠❎',
          'terminate': 'ter🤡😵‍💫😵',
          'fucker': 'Frog 🐸 errr 🌶',
          'fuckin': 'Frog 🐸 inn',
          'fuck': 'Frog 🐸',
          'bastard': 'bas 🤡🍉💥',
          'ass': 'aa 🍑💨🚀',
          'asshole': '🍑💨 🕳️',
          'shit': 'sh💩🍒',
          'slut': 'sl 👠💋💄🌶',
          'whore': 'who 🍑🍑🧹🦇',
          'pussy': 'pu 🐈🍑🍑',
          'pusey': 'pu pu 🐈🍑🍑',
          'pussi': 'pu pu 🐈🍑🍑',
          'pussye': 'pu pu 🐈🍑🍑',
          'horseshit': '💩🐴',
          'wanker': 'wa 🤭🍆💦',
          'wanking': 'wa 🤭🍆💦',
          'turd': 'tth 💩🐵🙈', 
          'twat': 'tw 🥴🧠❓',
          'spastic': '*',
          'nigga': '*',
          'nigra': '*',
          'frigger': 'fri 🍆💦🍑',
          'frig': 'fri 🍆💦🍑',
          'fatherfucker': 'father  🍆💦🍑',
          'dickhead': 'di 🍆🍆🍆',
          'dick': 'di 🍆🍆',
          'cunt': 'cu 🍆🍑💦',
          'crap': 'cr 💩🔥🤡',
          'sucker': 'su 🤤🍆🍑',
          'suck': 'su 🤤🍆🍑',
          'lick': 'li 🤤🍆🍑',
          'licker': 'li 🤤🍆🍑',
          'cocksucker': 'co 🤤🍆',
          'cock': 'co 🍆🍆',
          'child-fucker': '*',
          'childfucker': '*',
          'childfucker':'*',
          'bullshit': 'buul 🐂💩🍒',
          'brotherfucker': 'brother 🍆💦🍑',
          'bollocks': 'bo 🐂🍆🍆',
          'bloody': '🔪🩸',
          'bitch': 'bi 💆🏻‍♀️💅🏻🍑💩',
          'arsehole': '🍑💨 🕳️',
          'arsehead': '*',
          'arse': 'ar 🍑🍑',
          'Boob': '( ͜. ㅅ ͜. )',
          'Boobs': '( ͜. ㅅ ͜. )',
          'Boobies': '( ͜. ㅅ ͜. )',
          'Bubies': '( ͜. ㅅ ͜. )',
          'BhonsriWaala': 'bhors 🍆🍆',
          'Bhonsri': 'bh 🍆🍆',
          'chut': '🍆🍆🍑',
          'chodu': '🍆🍑💦',
          'chodra': '🍆🍑💦',
          'chod': '🍆🍑💦',
          'gaand': '🍆🍆',
          'gand': '🍆🍆',
          'kutte': 'woff 🐶',
          'kutteh': 'woff 🐶',
          'lunde': '🍆🍆',
          'Lavde ke baal':'Laa ✄🍑🍑',
          'Lavde ka baal':'Laa ✄🍑🍑',
          'Lavde ke bal':'Laa ✄🍑🍑',
          'Lavde ka bal': 'Laa ✄🍑🍑',
          'toto': '🍆🍑',
          'toota hua lund': 'to oo to 🍆',
          'bhadwe': '*',
          'bhosda': '*',
          'bhosri': '🍑🍑🍆',
          'benchod': 'ben 🍑🍆',
          'chutia': '🍑🍆', 
          'chutiya':'🍑🍆',
          'chutiye':'🍑🍆',
          'chutiye': '🍑🍆',
          'magi': '🍑💦',
          'baal':'b ✄🍆',
          'bal': 'b ✄🍆',
          'chudir': '🍆',
          'choda': '🍆🍆',
          'khanki': 'kh uh ah an kki',
          'madarchud': 'ma uh ad uhr ch od',
          'madarchod':'ma uh ad uhr ch od',
          'madarchodo': 'ma uh ad uhr ch do',
          'dhorshon': 'dh on ghor shon',
          'randimagi': 'rr uh ah en dd i mmh uh gi',
          'shukor': 'saussage',
          'lawra': 'la uw uwh ra',
          'chudirbai': 'ch uh uh di er bhai',
          'chudi': 'ch uh uh di',
            "comment oses-tu": "comment 😠💢😈 tu",
            "te faire payer": "te faire 📉💸",
            "tais-toi": "taaaais 🤐🔕-toi",
            "gâcher": "gâ 💀💩👻 cher",
            "détruire": "dé 💣🤯 truire",
            "brûler": "brû 🔥🔥 🔥 ler",
            "frapper": "👊💥🥊",
            "donner un coup": "🗡️💥 un coup!",
            "agression": "⚔️🧟‍♂️ grrrr",
            "attaque": "💣💥🧨 attaque!!",
            "tuer": "Pew Pew! 🔫💥",
            "tué": "🔫⚰️💀",
            "mourir": "⚰️😴💤",
            "mort": "💀🪦",
            "t’achever": "🔚⚰️👻",
            "éliminer": "élimi ❌🚷☠️ ner",
            "terminer": "ter 🤡🔚😵‍💫",
            "enfoiré": "en 🐸 foiré 🌶️",
            "putain de": "pu 🐸 tain 🔥",
            "baiser": "🐸🍆🍑",
            "putain": "pu 🍑 tain 💣",
            "salaud": "sa 🤡💩 laud",
            "cul": "cuu 🍑💨",
            "trou du cul": "🍑🕳️💨",
            "merde": "meee 💩🔥 rde",
            "salope": "sa 👠💋 loooope 🌶️",
            "pute": "puuuuu 🍑🍑 te",
            "chatte": "cha 🐈🍑🍑",
            "conneries": "con 💩🍒 ries",
            "branleur": "bra 🤭🍆💦 leur",
            "se branler": "se 🤭🍆💦 rrrrr",
            "crotte": "cr 💩 otte 🐵",
            "conne": "co 🧠 🤪 nne",
            "connard": "co 🍆😤 nard",
            "attardé": "* 🧠❌ (non-inclusif)",
            "*racial slur*": "*",
            "enculé": "en 🍑💦 culé",
            "tête de bite": "tête 🍆🍆",
            "bite": "bi 🍆🍆",
            "chatte": "cha 🐈💦",
            "connerie": "co 💩💥 nerrie",
            "suceur": "su 🤤🍆🍑 eur",
            "sucer": "su 🤤🍆🍑 er",
            "lécher": "lé 🤤💦 cher",
            "lècheur": "lè 🤤🍆🍑 eur",
            "suceur de bites": "suceur de 🍆🍆🍆",
            "enculeur de père": "encul 🍑💦 eur de 👨‍👦",
            "connerie": "co 💩💥 nnerie",
            "enculeur de frère": "encul 🍑💦 eur de 👬",
            "couilles": "cooo 🥜🥜 uilles",
            "putain de": "pu 🧨💄 tain de 🔪",
            "connasse": "con 💅🏻💁‍♀️🍑 asse",
            "trou du cul": "🍑💨 🕳️",
            "tête de cul": "tête de 🍑🧠",
            "nichons": "ni ( ͜. ㅅ ͜. ) chons",
            "seins": "( ͜. ㅅ ͜. )",
            "gros seins": "🥛🍈🍈 gros seins",
             "cómo te atreves": "cómo 😠💢😈 te atreves",
            "hacerte pagar": "hacerte 📉💸",
            "cállate": "caaa 🤐🔕 llate",
            "arruinar": "arru 💀💩👻 inar",
            "destruir": "des 💣🤯 truir",
            "quemar": "que 🔥🔥 mar 🔥",
            "golpear": "👊💥🥊",
            "dar un golpe": "🗡️💥 un golpe!",
            "asalto": "⚔️🧟‍♂️ grrr",
            "ataque": "💣💥🧨 ATAQUE!!",
            "matar": "Pew Pew! 🔫💥",
            "matado": "🔫⚰️💀",
            "morir": "⚰️😴💤",
            "muerto": "💀🪦",
            "acabar contigo": "🔚⚰️👻 contigo",
            "eliminar": "elimi ❌🚷☠️ nar",
            "terminar": "ter 🤡🔚😵‍💫 minar",
            "cabronazo": "cabro 🐸 n 🔥 azo",
            "maldito": "ma 🐸 l dito 🌶️",
            "follar": "🐸🍆🍑",
            "puta": "pu 🍑 ta 💣",
            "cerdo": "cer 🤡💩 do",
            "culo": "cuu 🍑💨",
            "agujero del culo": "🍑🕳️💨",
            "mierda": "miee 💩🔥 rda",
            "zorra": "zo 👠💋 rra 🌶️",
            "prostituta": "prooo 🍑🍑 sti 🧹 tuta",
            "coño": "co 🐈🍑🍑 ño",
            "tonterías": "ton 💩🍒 terías",
            "pajero": "pa 🤭🍆💦 jero",
            "hacerse una paja": "ha 🤭🍆💦 cerse",
            "caca": "ca 💩 ca 🐵",
            "idiota": "id 🧠 🤪 iota",
            "imbécil": "im 🍆😤 bécil",
            "retrasado": "* 🧠❌ (ofensivo)",
            "*racial slur*": "*",
            "hijo de puta": "hi 🍑💦 jo de 💣",
            "cabeza de pito": "cabeza 🍆🍆",
            "polla": "po 🍆🍆 lla",
            "coño": "co 🐈💦 ño",
            "estupidez": "es 💩💥 tupi dez",
            "chupador": "chu 🤤🍆🍑 pador",
            "chupar": "chu 🤤🍆🍑 par",
            "lamer": "la 🤤💦 mer",
            "lamedor": "la 🤤🍆🍑 medor",
            "chupapollas": "chupa 🍆🍆🍆 pollas",
            "violador de padres": "viola 🍑💦 dor de 👨‍👦",
            "mentira": "men 💩💥 tira",
            "violador de hermanos": "viola 🍑💦 dor de 👬",
            "cojones": "cooo 🥜🥜 jones",
            "maldita sea": "pu 🧨💄 tita 🔪 sea",
            "perra": "pe 💅🏻💁‍♀️🍑 rra",
            "agujero de culo": "🍑💨 🕳️",
            "cabeza de culo": "cabeza de 🍑🧠",
            "tetas": "te ( ͜. ㅅ ͜. ) tas",
            "senos": "( ͜. ㅅ ͜. )",
            "pechos grandes": "🥛🍈🍈 grandes",
            "come osi": "come 😠💢😈 osi",
            "farti pagare": "farti 📉💸 pagare",
            "stai zitto": "staaiii 🤐🔕 zitto",
            "rovinare": "rovi 💀💩👻 nare",
            "distruggere": "dis 💣🤯 truggere",
            "bruciare": "bru 🔥🔥 ciare 🔥",
            "colpire": "👊💥🥊",
            "dare un colpo": "🗡️💥 un colpo!",
            "aggressione": "⚔️🧟‍♂️ grrrrr",
            "attacco": "💣💥🧨 ATTACCO!!",
            "uccidere": "Pew Pew! 🔫💥",
            "ucciso": "🔫⚰️💀",
            "morire": "⚰️😴💤",
            "morto": "💀🪦",
            "farti fuori": "🔚⚰️👻 fuori!",
            "eliminare": "elimi ❌🚷☠️ nare",
            "terminare": "ter 🤡🔚😵‍💫 minare",
            "stronzo": "stron 🐸 zo 🌶️",
            "maledetto": "male 🐸 detto 💣",
            "scopare": "sco 🐸🍆🍑 pare",
            "cazzo": "ca 🍑 zzo 💥",
            "bastardo": "ba 🤡💩 stardo",
            "culo": "cuu 🍑💨 lo",
            "buco del culo": "🍑🕳️💨",
            "merda": "mer 💩🔥 da",
            "troia": "tro 👠💋 ia 🌶️",
            "puttana": "puu 🍑🍑 tana 🧹",
            "fica": "fi 🐈🍑🍑 ca",
            "cazzate": "💩 cazz 🍒 ate",
            "segaiolo": "se 🤭🍆💦 gaiolo",
            "segarsi": "se 🤭🍆💦 garsiii",
            "cacca": "ca 💩 ca 🐵",
            "cretina": "cre 🧠 🤪 tina",
            "coglione": "co 🍆😤 glione",
            "ritardato": "* 🧠❌ (non incluso)",
            "*slur razzista*": "*",
            "figlio di puttana": "figli 🍑💦 o di 💣 puttana",
            "testa di cazzo": "testa 🍆🍆",
            "pene": "pe 🍆🍆 ne",
            "fica": "fi 🐈💦 ca",
            "stronzata": "stron 💩💥 zata",
            "succhiacazzi": "su 🤤🍆🍑 cchiacazzi",
            "succhiare": "su 🤤🍆🍑 chiare",
            "leccare": "le 🤤💦 ccare",
            "leccaculo": "le 🤤🍆🍑 ccaculo",
            "succhiapene": "succhia 🍆🍆🍆 pene",
            "violatore di padri": "viola 🍑💦 tore di 👨‍👦",
            "stronzata": "stron 💩💥 zata",
            "violatore di fratelli": "viola 🍑💦 tore di 👬",
            "palle": "pa 🥜🥜 lle",
            "maledizione": "pu 🧨💄 tta 🔪 zione",
            "cagna": "ca 💅🏻💁‍♀️🍑 gna",
            "buco del culo": "🍑💨 🕳️",
            "testa di culo": "testa di 🍑🧠",
            "tette": "te ( ͜. ㅅ ͜. ) tte",
            "seni": "( ͜. ㅅ ͜. )",
            "tettone": "🥛🍈🍈 tettone",
            "كيف تجرؤ": "كيف 😠💢😈 تجرؤ",
            "أجعلك تدفع": "أجعلك 📉💸 تدفع",
            "اصمت": "اصممم 🤐🔕 ت",
            "تخريب": "تخر 💀💩👻 يب",
            "تدمير": "تدم 💣🤯 ييير",
            "احرق": "احر 🔥🔥 قق 🔥",
            "اضرب": "👊💥🥊",
            "أعطي ضربة": "🗡️💥 ضربة قاضية",
            "اعتداء": "⚔️🧟‍♂️ إعتدااااء!",
            "هجوم": "💣💥🧨 هجووووم!",
            "اقتل": "Pew Pew! 🔫💥",
            "قُتل": "🔫⚰️💀",
            "موت": "⚰️😴💤",
            "ميت": "💀🪦",
            "سأنهيك": "🔚⚰️👻 فيك",
            "إزالة": "إزا ❌🚷☠️ له",
            "إنهاء": "إن 🤡🔚😵‍💫 هاااء",
            "ابن القحبة": "ابن 🐸🔥 القحبة 🌶️",
            "لعنة": "لعنة 🐸🔥💣",
            "نيك": "نيي 🐸🍆🍑 ك",
            "قحبة": "قح 🍑 به 💣",
            "كلب ابن كلب": "كل 🤡💩ب ابن كلب",
            "طيز": "طي 🍑ز💨",
            "شرج": "🍑🕳️💨",
            "خرا": "خر 💩🔥 ااا",
            "شرموطة": "شر 👠💋 مووطة 🌶️",
            "عاهرة": "عاا 🍑🍑 هرة 🧹",
            "كس": "ك 🐈🍑🍑 س",
            "تفاهة": "تف 💩🍒 اهة",
            "مجهود يدوي 🤭": "🤭🍆💦 شغل يدوي",
            "يفش خلقه": "يفش 🤭🍆💦 خلقه",
            "براز": "برا 💩 ز 🐵",
            "غبي": "غ 🧠 🤪 بي",
            "أهبل": "أه 🍆😤 بل",
            "متخلف": "* 🧠❌ (غير مقبول)",
            "*إهانة عنصرية*": "*",
            "ابن الزانية": "ابن 🍑💦 💣 زانية",
            "رأس زب": "رأس 🍆🍆",
            "زب": "ز 🍆🍆 ب",
            "كس": "ك 🐈💦 س",
            "سخافة": "سخ 💩💥 افة",
            "مص زب": "مص 🤤🍆🍑 زب",
            "يمص": "يمص 🤤🍆🍑",
            "يلحس": "يلح 🤤💦 س",
            "لحاس": "لح 🤤🍆🍑 اس",
            "مصاص زب": "مصاص 🍆🍆🍆",
            "مغتصب الأب": "مغتصب 🍑💦 الأب 👨‍👦",
            "خراء": "خر 💩💥 اااء",
            "مغتصب الأخ": "مغتصب 🍑💦 الأخ 👬",
            "خصيتين": "خصي 🥜🥜 تين",
            "يلعن أبوك": "يلعن 🧨💄 أبوك 🔪",
            "كلبة": "كل 💅🏻💁‍♀️🍑 بة",
            "شرج": "🍑💨 🕳️",
            "رأس الطيز": "رأس 🍑🧠",
            "صدر": "صـ ( ͜. ㅅ ͜. ) ـدر",
            "ثدي": "( ͜. ㅅ ͜. )",
            "صدر كبير": "🥛🍈🍈 كبيير",
      };

      // Regular expression to match all key phrases in the dictionary
      const phrasesRegex = new RegExp(
        Object.keys(slangDictionary)
          .sort((a, b) => b.length - a.length) // Sort by length to prioritize specific cases
          .map((phrase) => phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) // Escape special characters
          .join('|'),
        'gi'
      );

      // Perform replacement using the regular expression
      const filteredText = inputText.replace(phrasesRegex, (match) => {
        const replacement = slangDictionary[match.toLowerCase()];
        return replacement || match;
      });

      // Return the filtered text as a string
      return filteredText;


};
